version: '3'

volumes:
  static:

services:

  backend:
    build: ./stripe_case/
    env_file: .env
    volumes:
      - static:/static

  gateway:
    container_name: stripe_case_gateway
    build: ./nginx/
    volumes:
      - static:/staticfiles/
    ports:
      - 5000:80
    depends_on:
      - backend
